config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get '/' => "home#top"
  get '/login_check' => "home#login_check"
  get '/creation' => "home#creation"
  get '/talk' => "home#talk"
  get '/add_friend' => "home#add_friend"
  get '/serch_friend' => "home#serch_friend"
  get '/find' => "home#find"
  post '/find' => "home#find"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'application'
    before_action :authenticate_account!, only: :login_check
  
  def top
  end
  
  def login_check
      @account = current_account
      @msg = 'you logined at : ' + @account.current_sign_in_at.to_s
  end
  
  def creation
      @account = current_account
      @msg = 'you logined at : ' + @account.current_sign_in_at.to_s
  end
  
  def talk
      @account = current_account
      @msg = 'you logined at : ' + @account.current_sign_in_at.to_s
  end
  
  def add_friend
      @account = current_account
      @msg = 'you logined at : ' + @account.current_sign_in_at.to_s
  end
  
  def find
      @accounts = Array.new
      if request.post? then
          @accounts = account.where email: params[:find]
      end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/add_friend.html.erb
<%= render :file => "/home/login_check" %>
<br>
<br>
<br>
<h2><%= link_to('友達名','/') %></h2>
<br>
<br>

app/views/home/creation.html.erb
<%= render :file => "/home/login_check" %>
<br>
<br>
<br>
<h2><%= link_to('友達検索','/serch_friend') %></h2>
<br>
<br>

app/views/home/login_check.html.erb
<div class="signout">
  <%= link_to 'サインアウト!&gt;&gt;'.html_safe, destroy_account_session_path, method: :delete %>
</div>
<h1><%= @account.email %>さんようこそ</h1>
<p><%= @msg %></p>
<div class="main">
  <%= link_to('友達','/add_friend') %>
</div>
<div class="main">
  <%= link_to('トーク','/talk') %>
</div>
<div class="main">
  <%= link_to('設定','/creation') %>
</div>

app/views/home/serch_friend.html.erb
<h1>LINE</h1>
<table>
<%= form_tag(controller: 'home', action: 'find') do %>
<tr><th>Find</th>
    <td><% text_field_tag("find") %></td>
</tr>
<tr><th></th>
    <td><% submit_tag("Click") %></td>
</tr>
<% end %>
</table>
<hr>
<table>
  <tr>
    <th>Mail</th>
  </tr>
  <% @accounts.each do |obj| %>
  <tr>
    <td><%= obj.email %></td>
  </tr>
  <% end %>
</table>

app/views/home/talk.html.erb
<%= render :file => "/home/login_check" %>
<br>
<br>
<br>
<h2><%= link_to('友達名(konan)','/') %></h2>
<br>
<br>

app/views/home/top.html.erb
<div class="head">
  <h1>LINE</h1>
</div>
<br>
<br>
<div class="login">
  <%= link_to 'ログイン!&gt;&gt;'.html_safe, {action: 'login_check'} %>
</div>
<div class="signOut">
  <%= link_to 'サインアウト!&gt;&gt;'.html_safe, destroy_account_session_path, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Free</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>